spring.application.name=Right
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${DB_NAME:jdbc:postgresql://dpg-d7phroa8qa3s73c3jl60-a.oregon-postgres.render.com:5432/rightone?sslmode=require}
spring.datasource.username=${DB_USERNAME:rightone_user}
spring.datasource.password=${DB_PASSWORD:yqRCQRveqeG5izZvE45bLj5y033bifRg}

# JPA / Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# File Upload Configuration
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Logging
logging.level.org.springframework.security=DEBUG

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=kushpatel0606@gmail.com
spring.mail.password=pzid bqib oczq nyqc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
